version: '3.1'

services:
  master1:
    container_name: master1
    build:
      context: .
      dockerfile: Dockerfile
    image: master
    volumes:
      - ./configurations.json:/master/configurations.json
    ports:
      - "8081:8080"
  master2:
    container_name: master2
    image: master
    volumes:
      - ./configurations.json:/master/configurations.json
    ports:
      - "8082:8080"
  master3:
    container_name: master3
    image: master
    volumes:
      - ./configurations.json:/master/configurations.json
    ports:
      - "8083:8080"
  master4:
    container_name: master4
    image: master
    volumes:
      - ./configurations.json:/master/configurations.json
    ports:
      - "8084:8080"