version: '3.1'

services:
  master1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ZK_SERVERS: /master/zkServers.mini
    ports:
      - "8081:8080"
  master2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ZK_SERVERS: /master/zkServers.mini
    ports:
      - "8082:8080"
  master3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ZK_SERVERS: /master/zkServers.mini
    ports:
      - "8083:8080"
  master4:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ZK_SERVERS: /master/zkServers.mini
    ports:
      - "8084:8080"